// <auto-generated />
using System;
using Comies.Core.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace comies_services.Migrations
{
    [DbContext(typeof(ComiesContext))]
    partial class ComiesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Comies.Structures.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CostumerId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CostumerId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Comies.Structures.Models.Costumer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MemberSince")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Costumers");
                });

            modelBuilder.Entity("Comies.Structures.Models.Ingredient", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("ComponentStoreId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(6)");

                    b.Property<int?>("ProductStoreId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.HasKey("ProductId", "IngredientId");

                    b.HasIndex("ComponentCode", "ComponentStoreId");

                    b.HasIndex("ProductCode", "ProductStoreId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("Comies.Structures.Models.Operator", b =>
                {
                    b.Property<string>("Nickname")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId1")
                        .HasColumnType("int");

                    b.Property<int>("StoreId2")
                        .HasColumnType("int");

                    b.HasKey("Nickname", "StoreId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("StoreId1", "StoreId2");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("Comies.Structures.Models.Order", b =>
                {
                    b.Property<DateTime>("Placed")
                        .HasColumnType("datetime2");

                    b.Property<int>("CostumerId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("AddressId")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliverType")
                        .HasColumnType("int");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<string>("OperatorNickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("OperatorStoreId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StoreId1")
                        .HasColumnType("int");

                    b.Property<int>("StoreId2")
                        .HasColumnType("int");

                    b.HasKey("Placed", "CostumerId", "StoreId");

                    b.HasIndex("AddressId");

                    b.HasIndex("CostumerId");

                    b.HasIndex("OperatorNickname", "OperatorStoreId");

                    b.HasIndex("StoreId1", "StoreId2");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Comies.Structures.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Group")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Done")
                        .HasColumnType("bit");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("OrderCostumerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStoreId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("ProductStoreId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("StoreId1")
                        .HasColumnType("int");

                    b.Property<int>("StoreId2")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "Group", "ProductId", "StoreId");

                    b.HasIndex("ProductCode", "ProductStoreId");

                    b.HasIndex("StoreId1", "StoreId2");

                    b.HasIndex("OrderPlaced", "OrderCostumerId", "OrderStoreId");

                    b.ToTable("OrdersItems");
                });

            modelBuilder.Entity("Comies.Structures.Models.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("CostumerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DDD")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("Id");

                    b.HasIndex("CostumerId");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("Comies.Structures.Models.Product", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("StoreId")
                        .HasMaxLength(9)
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ComboCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("ComboId")
                        .HasColumnType("int");

                    b.Property<int>("ComboStoreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Display")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<double>("Minimum")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCategoryCode")
                        .HasColumnType("nvarchar(6)");

                    b.Property<int?>("ProductCategoryStoreId")
                        .HasColumnType("int");

                    b.Property<int>("SellUnity")
                        .HasColumnType("int");

                    b.Property<int>("StoreId1")
                        .HasColumnType("int");

                    b.Property<int>("StoreId2")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Code", "StoreId");

                    b.HasIndex("ComboCode", "ComboStoreId");

                    b.HasIndex("ProductCategoryCode", "ProductCategoryStoreId");

                    b.HasIndex("StoreId1", "StoreId2");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Comies.Structures.Models.ProductCategory", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Description")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentCategoryCode")
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentCategoryStoreId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId1")
                        .HasColumnType("int");

                    b.Property<int>("StoreId2")
                        .HasColumnType("int");

                    b.HasKey("Code", "StoreId");

                    b.HasIndex("ParentCategoryCode", "ParentCategoryStoreId");

                    b.HasIndex("StoreId1", "StoreId2");

                    b.ToTable("ProductsCategories");
                });

            modelBuilder.Entity("Comies.Structures.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId1")
                        .HasColumnType("int");

                    b.Property<int>("StoreId2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreId1", "StoreId2");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Comies.Structures.Models.ProfileDetails", b =>
                {
                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("PermissionCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Allowed")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowedToAdd")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowedToDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowedToGet")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowedToUpdate")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("StoreId1")
                        .HasColumnType("int");

                    b.Property<int>("StoreId2")
                        .HasColumnType("int");

                    b.HasKey("ProfileId", "PermissionCode", "StoreId");

                    b.HasIndex("StoreId1", "StoreId2");

                    b.ToTable("ProfilesDetails");
                });

            modelBuilder.Entity("Comies.Structures.Models.Stock", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<double>("Actual")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MainSupplierId")
                        .HasColumnType("int");

                    b.Property<double>("Maximum")
                        .HasColumnType("float");

                    b.Property<double>("Minimum")
                        .HasColumnType("float");

                    b.Property<int>("StockUnity")
                        .HasColumnType("int");

                    b.Property<int>("StoreId1")
                        .HasColumnType("int");

                    b.Property<int>("StoreId2")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierStoreId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "StoreId");

                    b.HasIndex("StoreId1", "StoreId2");

                    b.HasIndex("SupplierId", "SupplierStoreId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Comies.Structures.Models.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("OtherCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId1")
                        .HasColumnType("int");

                    b.Property<int>("StoreId2")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("UnityPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id", "StoreId");

                    b.HasIndex("StoreId1", "StoreId2");

                    b.ToTable("StocksMovements");
                });

            modelBuilder.Entity("Comies.Structures.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyNickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MemberSince")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId1")
                        .HasColumnType("int");

                    b.Property<int>("StoreId2")
                        .HasColumnType("int");

                    b.HasKey("Id", "StoreId");

                    b.HasIndex("AddressId");

                    b.HasIndex("PhoneId");

                    b.HasIndex("StoreId1", "StoreId2");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Comies.Structures.Models.StoreProperty", b =>
                {
                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("AllowOverride")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ParentId1")
                        .HasColumnType("int");

                    b.Property<string>("ParentKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ParentStoreId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId1")
                        .HasColumnType("int");

                    b.Property<int>("StoreId2")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParentId", "Key", "StoreId");

                    b.HasIndex("StoreId1", "StoreId2");

                    b.HasIndex("ParentId1", "ParentKey", "ParentStoreId");

                    b.ToTable("StoresProperties");
                });

            modelBuilder.Entity("Comies.Structures.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MemberSince")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId1")
                        .HasColumnType("int");

                    b.Property<int>("StoreId2")
                        .HasColumnType("int");

                    b.HasKey("Id", "StoreId");

                    b.HasIndex("AddressId");

                    b.HasIndex("PhoneId");

                    b.HasIndex("StoreId1", "StoreId2");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Comies.Structures.Models.Address", b =>
                {
                    b.HasOne("Comies.Structures.Models.Costumer", "Costumer")
                        .WithMany("Addresses")
                        .HasForeignKey("CostumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Costumer");
                });

            modelBuilder.Entity("Comies.Structures.Models.Ingredient", b =>
                {
                    b.HasOne("Comies.Structures.Models.Product", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentCode", "ComponentStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comies.Structures.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductCode", "ProductStoreId");

                    b.Navigation("Component");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Comies.Structures.Models.Operator", b =>
                {
                    b.HasOne("Comies.Structures.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comies.Structures.Models.Store", "Store")
                        .WithMany("Operators")
                        .HasForeignKey("StoreId1", "StoreId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Comies.Structures.Models.Order", b =>
                {
                    b.HasOne("Comies.Structures.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comies.Structures.Models.Costumer", "Costumer")
                        .WithMany("Orders")
                        .HasForeignKey("CostumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comies.Structures.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorNickname", "OperatorStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comies.Structures.Models.Store", "Store")
                        .WithMany("Orders")
                        .HasForeignKey("StoreId1", "StoreId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Costumer");

                    b.Navigation("Operator");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Comies.Structures.Models.OrderItem", b =>
                {
                    b.HasOne("Comies.Structures.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductCode", "ProductStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comies.Structures.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId1", "StoreId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comies.Structures.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderPlaced", "OrderCostumerId", "OrderStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Comies.Structures.Models.Phone", b =>
                {
                    b.HasOne("Comies.Structures.Models.Costumer", "Costumer")
                        .WithMany("Phones")
                        .HasForeignKey("CostumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Costumer");
                });

            modelBuilder.Entity("Comies.Structures.Models.Product", b =>
                {
                    b.HasOne("Comies.Structures.Models.Product", "Combo")
                        .WithMany()
                        .HasForeignKey("ComboCode", "ComboStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comies.Structures.Models.ProductCategory", null)
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryCode", "ProductCategoryStoreId");

                    b.HasOne("Comies.Structures.Models.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId1", "StoreId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Comies.Structures.Models.ProductCategory", b =>
                {
                    b.HasOne("Comies.Structures.Models.ProductCategory", "ParentCategory")
                        .WithMany("ChildrenCategories")
                        .HasForeignKey("ParentCategoryCode", "ParentCategoryStoreId");

                    b.HasOne("Comies.Structures.Models.Store", "Store")
                        .WithMany("ProductCategories")
                        .HasForeignKey("StoreId1", "StoreId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentCategory");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Comies.Structures.Models.Profile", b =>
                {
                    b.HasOne("Comies.Structures.Models.Store", "Store")
                        .WithMany("Profiles")
                        .HasForeignKey("StoreId1", "StoreId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Comies.Structures.Models.ProfileDetails", b =>
                {
                    b.HasOne("Comies.Structures.Models.Profile", "Profile")
                        .WithMany("ProfileDetails")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comies.Structures.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId1", "StoreId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Comies.Structures.Models.Stock", b =>
                {
                    b.HasOne("Comies.Structures.Models.Store", "Store")
                        .WithMany("Stocks")
                        .HasForeignKey("StoreId1", "StoreId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comies.Structures.Models.Supplier", null)
                        .WithMany("Stocks")
                        .HasForeignKey("SupplierId", "SupplierStoreId");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Comies.Structures.Models.StockMovement", b =>
                {
                    b.HasOne("Comies.Structures.Models.Store", "Store")
                        .WithMany("StockMovements")
                        .HasForeignKey("StoreId1", "StoreId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Comies.Structures.Models.Store", b =>
                {
                    b.HasOne("Comies.Structures.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comies.Structures.Models.Phone", "Phone")
                        .WithMany()
                        .HasForeignKey("PhoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comies.Structures.Models.Store", "Store")
                        .WithMany("Stores")
                        .HasForeignKey("StoreId1", "StoreId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Phone");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Comies.Structures.Models.StoreProperty", b =>
                {
                    b.HasOne("Comies.Structures.Models.Store", "Store")
                        .WithMany("StoreProperties")
                        .HasForeignKey("StoreId1", "StoreId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comies.Structures.Models.StoreProperty", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId1", "ParentKey", "ParentStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Comies.Structures.Models.Supplier", b =>
                {
                    b.HasOne("Comies.Structures.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comies.Structures.Models.Phone", "Phone")
                        .WithMany()
                        .HasForeignKey("PhoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comies.Structures.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId1", "StoreId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Phone");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Comies.Structures.Models.Costumer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("Comies.Structures.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Comies.Structures.Models.ProductCategory", b =>
                {
                    b.Navigation("ChildrenCategories");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Comies.Structures.Models.Profile", b =>
                {
                    b.Navigation("ProfileDetails");
                });

            modelBuilder.Entity("Comies.Structures.Models.Store", b =>
                {
                    b.Navigation("Operators");

                    b.Navigation("Orders");

                    b.Navigation("ProductCategories");

                    b.Navigation("Products");

                    b.Navigation("Profiles");

                    b.Navigation("StockMovements");

                    b.Navigation("Stocks");

                    b.Navigation("StoreProperties");

                    b.Navigation("Stores");
                });

            modelBuilder.Entity("Comies.Structures.Models.StoreProperty", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Comies.Structures.Models.Supplier", b =>
                {
                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
